### ISSUE TITLE
Publish into julia package  manager

### ISSUE THREAD

**Issue by r-chris** [c42f/Displaz.jl#11]
This will make automated build testing easier for anyone interested in putting `Displaz` into their `REQUIRE` file

**Comment by c42f** [comment]
Good idea, sorry to be a bit slow about it.

Let's try for a 0.0.1 - julialang/METADATA.jl#6436

**Comment by r-chris** [comment]
Thanks! Looking forward to this.

**Comment by c42f** [comment]
Tony merged this.  He said I didn't have enough tests, which is unarguably true!
